- name: Installing Roboshop "{{component}}"
  import_role:
    name: common
    tasks_from: app_setup

- name: Installing mongodb and loading data
  import_role:
    name: common
    tasks_from: mongodb_setup

- name: restarting service
  import_role:
    name: common
    tasks_from: service