- name: User for Roboshop
  become: yes
  hosts: user
  tasks:
    - name: Disabing and enabling nodejs:18
      shell: "dnf module disable nodejs -y && dnf module enable nodejs:18 -y"

    - name: Installing Node js
      package:
        name: nodejs
        state: present
        update_cache: yes

    - name: Creating user
      user:
        name: roboshop
        state: present

    - name: Creating app directory
      file:
        name: /app
        state: directory

    - name: Downloading and unarchiving app data
      unarchive:
        src:   https://roboshop-builds.s3.amazonaws.com/user.zip
        dest: /app
        remote_src: yes

    - name: Installing dependencies
      shell: npm install
      args:
        chdir: /app

    - name: Copying user.service file
      copy:
        src: user.service
        dest: /etc/systemd/system/user.service

    - name: Reloading daemon
      systemd_service:
        daemon_reload: true

    - name: Enabling and starting user service
      service:
        name: user
        state: restarted
        enabled: yes

    - name: Copying mongodb repo for installing mongoshell
      copy:
        src: mongodb.repo
        dest: /etc/yum.repos.d/mongodb.repo

    - name: Installing mongodb-shell
      package:
        name: mongodb-org-shell
        state: present
        update_cache: yes

    - name: Checking mongodb data
      command: mongo --host mongodb.challa.cloud --quiet --eval 'db = db.getSiblingDB("users"); db = db.users.count()'
      register: users_count

    - name: Loading User data to mongodb
      command: mongo --host mongodb.challa.cloud < app/schema/user.js
      when: users_count.stdout == "0"

    - name: Restarting User service
      service:
        name: catalogue
        state: restarted